databases:
  - name: task-database
    plan: free
    databaseName: tasks
    user: tasks_user
services:
  - type: web
    name: go-getter
    env: go
    buildCommand: go build -o bin/app cmd/server
    startCommand: ./bin/app
    envVars:
      - key: PORT
        value: 8275
        generateValue: true
      - key: DATABASE_URL
        name: tasks-database
        property: connectionString